### ISSUE TITLE
BufferMgrConcurrencyTest failure

### ISSUE THREAD

**Issue by jserv** [vanilladb/vanillacore#3]
While executing `mvn package`, I encountered an error as following:
```
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 10.084 sec <<< FAILURE! - in org.vanilladb.core.storage.buffer.BufferMgrConcurrencyTest
testRepinning(org.vanilladb.core.storage.buffer.BufferMgrConcurrencyTest)  Time elapsed: 10.083 sec  <<< ERROR!
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1471)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1469)
	at org.vanilladb.core.storage.buffer.BufferMgr.repin(BufferMgr.java:298)
	at org.vanilladb.core.storage.buffer.BufferMgr.pin(BufferMgr.java:143)
	at org.vanilladb.core.storage.buffer.BufferMgrConcurrencyTest.testRepinning(BufferMgrConcurrencyTest.java:60)
```

Platform information:
```
$ mvn --version
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_102, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
OS name: "linux", version: "4.6.0-10-generic", arch: "amd64", family: "unix"
```

**Comment by SLMT** [comment]
Thank you for your report. We have identified the problem and we are now working on this.

**Comment by SLMT** [comment]
@jserv The bug should have been fixed. You can try it again.

**Comment by jserv** [comment]
Confirmed and verified.
